POST http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json

{
    "name": "My product",
    "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json

###
GET http://localhost:8000/products/616b3ecd-649a-47a0-a2bd-e6ce9bfc184c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json

###
PUT http://localhost:8000/products/616b3ecd-649a-47a0-a2bd-e6ce9bfc184c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json

{
    "name": "My updated product",
    "price": 150
}

###

DELETE http://localhost:8000/products/616b3ecd-649a-47a0-a2bd-e6ce9bfc184c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json
